// map from the state abbreviations to the grid location
// use the example cartogram from the assignment 4 page
// as a tepmlate for the locations of the states in the grid
state_locations = {
	"AK" : { row: 0, col: 0},
	"HI" : { row: 7, col: 0},
	"WA" : { row: 2, col: 1},
	"OR" : { row: 3, col: 1},
	"CA" : { row: 4, col: 1},
	"ID" : { row: 2, col: 2},
	"NV" : { row: 3, col: 2},
	"UT" : { row: 4, col: 2},
	"AZ" : { row: 5, col: 2},
	"MT" : { row: 2, col: 3},
	"WY" : { row: 3, col: 3},
	"CO" : { row: 4, col: 3},
	"NM" : { row: 5, col: 3},
	"ND" : { row: 2, col: 4},
	"SD" : { row: 3, col: 4},
	"NE" : { row: 4, col: 4},
	"KS" : { row: 5, col: 4},
	"OK" : { row: 6, col: 4},
	"TX" : { row: 7, col: 4},
	"MN" : { row: 2, col: 5},
	"IA" : { row: 3, col: 5},
	"MO" : { row: 4, col: 5},
	"AR" : { row: 5, col: 5},
	"LA" : { row: 6, col: 5},
	"IL" : { row: 2, col: 6},
	"IN" : { row: 3, col: 6},
	"KY" : { row: 4, col: 6},
	"TN" : { row: 5, col: 6},
	"MS" : { row: 6, col: 6},
	"WI" : { row: 2, col: 7},
	"OH" : { row: 3, col: 7},
	"WV" : { row: 4, col: 7},
	"NC" : { row: 5, col: 7},
	"AL" : { row: 6, col: 7},
	"MI" : { row: 2, col: 8},
	"PA" : { row: 3, col: 8},
	"VA" : { row: 4, col: 8},
	"SC" : { row: 5, col: 8},
	"GA" : { row: 6, col: 8},
	"NY" : { row: 2, col: 9},
	"NJ" : { row: 3, col: 9},
	"MD" : { row: 4, col: 9},
	"DE" : { row: 5, col: 9},
	"FL" : { row: 7, col: 9},
	"VT" : { row: 1, col: 10},
	"RI" : { row: 2, col: 10},
	"CT" : { row: 3, col: 10},
	"DC" : { row: 4, col: 10},
	"ME" : { row: 0, col: 11},
	"NH" : { row: 1, col: 11},
	"MA" : { row: 2, col: 11},
}

// source for the images of presidents
// https://en.wikipedia.org/wiki/List_of_Presidents_of_the_United_States
images = {
	"2016" : "Trump.jpg",
	"2012" : "Obama.jpg",
	"2008" : "Obama.jpg",
	"2004" : "BushGW.jpg",
	"2000" : "BushGW.jpg",
	"1996" : "Clinton.jpg",
	"1992" : "Clinton.jpg",
	"1988" : "BushGHW.jpg",
	"1984" : "Reagan.jpg",
	"1980" : "Reagan.jpg",
	"1976" : "Carter.jpg",
	"1972" : "Nixon.jpg",
	"1968" : "Nixon.jpg",
	"1964" : "Johnson.jpg",
	"1960" : "Kennedy.jpg",
	"1956" : "Eisenhower.jpg",
	"1952" : "Eisenhower.jpg",
	"1948" : "Truman.jpg",
	"1944" : "Roosevelt.jpg",
	"1940" : "Roosevelt.jpg"
}
